https://archive.org/stream/in.ernet.dli.2015.112246/2015.112246.East-Of-Eden-Steinbeck_djvu.txt

In [53]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import ggplot
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [48]:
url = "https://raw.githubusercontent.com/austinchan1/Data-620---Web-Analytics/master/Homework%20Week%204%20-%20Part%202/East_of_Eden.txt"

page = requests.get(url)
corpus = page.text

In [49]:
tokens = word_tokenize(corpus)
words = [word.lower() for word in tokens if word.isalpha()]
stems = [PorterStemmer().stem(word) for word in words]

In [50]:
def word_counter(string):
    counts = dict()
    
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
            
    return(counts)


word_counts = word_counter(stems)

In [61]:
WordCountDF = pd.DataFrame.from_dict(word_counts, orient="index")

WordCountDF.columns = ["Word_Counts"]

Top200_Sorted = WordCountDF.sort_values(by = "Word_Counts", ascending = False)[0:200]

Top200_Sorted.reset_index(level = 0, inplace = True)

In [62]:


Top200_Sorted

        index  Word_Counts
0         the         8506
1         and         6980
2           a         4734
3          to         4596
4           i         4088
5          he         3913
6         you         3512
7          of         3324
8          it         3156
9          in         2773
10        was         2424
11        his         2332
12        she         2090
13          t         2074
14       said         1976
15        her         1889
16          s         1867
17       that         1801
18        had         1272
19         on         1200
20        not         1164
21        for         1121
22       with         1075
23       adam         1040
24        him         1024
25        but         1004
26         at          967
27       have          826
28        don          813
29       they          788
..        ...          ...
170       new          147
171     hands          147
172     first          146
173       joe          146
174    turned          145
175   brother          143
176     money          142
177    wanted          141
178      ever          139
179      abra          139
180      boys          139
181       has          136
182     cathy          136
183     under          135
184   himself          135
185       sat          135
186      mean          134
187     while          134
188     which          133
189       our          131
190   against          130
191   salinas          128
192  hamilton          125
193      tlie          124
194     great          124
195      must          123
196     night          122
197     world          122
198      kind          120
199      talk          120

[200 rows x 2 columns]